app:
  name: test 0
server:
   shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10m
  task:
    execution:
      pool:
        max-size: 50
        queue-capacity: 100
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 10m
  